# Generated by Django 4.0.8 on 2022-10-09 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='price',
        ),
    ]
