# Generated by Django 4.1.2 on 2022-10-12 14:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_remove_cart_date_added"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdersPerformed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(blank=True, max_length=250)),
                (
                    "orderdate",
                    models.DateTimeField(
                        default=datetime.datetime(2022, 10, 12, 18, 33, 56, 684237)
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cart.cart"
                    ),
                ),
            ],
            options={
                "db_table": "OrdersPerformed",
            },
        ),
        migrations.CreateModel(
            name="OrdersItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cart.product"
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cart.ordersperformed",
                    ),
                ),
            ],
            options={
                "db_table": "OrdersItems",
            },
        ),
        migrations.AddConstraint(
            model_name="ordersitems",
            constraint=models.UniqueConstraint(
                fields=("product", "store"), name="unique_product_order"
            ),
        ),
    ]
