# Generated by Django 4.1.2 on 2022-10-12 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_ordersperformed_ordersitems_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrdersItems",
            new_name="OrdersItem",
        ),
        migrations.AlterField(
            model_name="ordersperformed",
            name="orderdate",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 12, 18, 43, 59, 589189)
            ),
        ),
        migrations.AlterModelTable(
            name="ordersitem",
            table="OrdersItem",
        ),
    ]
