# Generated by Django 4.1.2 on 2022-10-12 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_rename_ordersitems_ordersitem_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ordersitem",
            name="unique_product_order",
        ),
        migrations.RenameField(
            model_name="ordersitem",
            old_name="store",
            new_name="order",
        ),
        migrations.AlterField(
            model_name="ordersperformed",
            name="orderdate",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 12, 18, 56, 32, 55544)
            ),
        ),
        migrations.AddConstraint(
            model_name="ordersitem",
            constraint=models.UniqueConstraint(
                fields=("product", "order"), name="unique_product_order"
            ),
        ),
    ]
