# Generated by Django 4.1.2 on 2022-10-12 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0007_remove_ordersitem_unique_product_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordersperformed",
            name="orderdate",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 12, 19, 14, 40, 60654)
            ),
        ),
    ]
