# Generated by Django 4.1.2 on 2022-10-12 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0008_alter_ordersperformed_orderdate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordersperformed",
            name="order_id",
        ),
        migrations.AlterField(
            model_name="ordersperformed",
            name="orderdate",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 12, 19, 19, 8, 635589)
            ),
        ),
    ]
